services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    restart: unless-stopped
    command:
      - "-jar"
      - "DynamoDBLocal.jar"
      - "-inMemory"
      - "-sharedDb"
